---
abstract: 'Perl extension to simulate rolling loaded dice'
author:
  - 'Miles Gould <miles@assyrian.org.uk>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Dice-Loaded
requires:
  AutoLoader: 0
  Carp: 0
  Exporter: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 2.0300
  Statistics::Distributions: 1.02
  Test::More: 0
  strict: 0
  warnings: 0
version: 0.002
